# This is a basic workflow to help you get started with Actions

name: Publish to buf.build

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the main branch
    pull_request:
        branches: [main]
        paths:
            - "**.proto"
    push:
        branches: [main]
        paths:
            - "**.proto"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0 # gives standard-version access to all previous commits
            - name: buf-setup
              uses: bufbuild/buf-setup-action@v1.4.0
            - name: buf-lint
              uses: bufbuild/buf-lint-action@v1.0.0
            - uses: bufbuild/buf-breaking-action@v1
              with: # The 'main' branch of the GitHub repository that defines the module.
                  against: "https://github.com/${{ github.repository }}.git#branch=main"

            - name: standard-version
              run: |
                  git config user.name "GitHub Actions Bot"
                  git config user.email "${{ github.repository_owner }}@users.noreply.github.com"
                  npx standard-version
            - name: publish tag
              id: publish_tag
              run: |
                  git push --follow-tags origin main
                  echo ::set-output name=tag_name::$(git describe HEAD --abbrev=0)
            - name: Push to buf.build
              run: BUF_TOKEN="${{ secrets.BUF_TOKEN }}" buf push --tag ${{ steps.publish_tag.outputs.tag_name }}
